/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardTranscricaoRouteImport } from './routes/dashboard/transcricao'
import { Route as DashboardPacientesRouteImport } from './routes/dashboard/pacientes'
import { Route as DashboardExerciciosRouteImport } from './routes/dashboard/exercicios'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'
import { Route as DashboardPacientesIndexRouteImport } from './routes/dashboard/pacientes.index'
import { Route as DashboardPacientesIdRouteImport } from './routes/dashboard/pacientes.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTranscricaoRoute = DashboardTranscricaoRouteImport.update({
  id: '/transcricao',
  path: '/transcricao',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPacientesRoute = DashboardPacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExerciciosRoute = DashboardExerciciosRouteImport.update({
  id: '/exercicios',
  path: '/exercicios',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPacientesIndexRoute = DashboardPacientesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardPacientesRoute,
} as any)
const DashboardPacientesIdRoute = DashboardPacientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardPacientesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/exercicios': typeof DashboardExerciciosRoute
  '/dashboard/pacientes': typeof DashboardPacientesRouteWithChildren
  '/dashboard/transcricao': typeof DashboardTranscricaoRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/pacientes/$id': typeof DashboardPacientesIdRoute
  '/dashboard/pacientes/': typeof DashboardPacientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/exercicios': typeof DashboardExerciciosRoute
  '/dashboard/transcricao': typeof DashboardTranscricaoRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/pacientes/$id': typeof DashboardPacientesIdRoute
  '/dashboard/pacientes': typeof DashboardPacientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/exercicios': typeof DashboardExerciciosRoute
  '/dashboard/pacientes': typeof DashboardPacientesRouteWithChildren
  '/dashboard/transcricao': typeof DashboardTranscricaoRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/pacientes/$id': typeof DashboardPacientesIdRoute
  '/dashboard/pacientes/': typeof DashboardPacientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/admin'
    | '/dashboard/exercicios'
    | '/dashboard/pacientes'
    | '/dashboard/transcricao'
    | '/dashboard/'
    | '/dashboard/pacientes/$id'
    | '/dashboard/pacientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/admin'
    | '/dashboard/exercicios'
    | '/dashboard/transcricao'
    | '/dashboard'
    | '/dashboard/pacientes/$id'
    | '/dashboard/pacientes'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/admin'
    | '/dashboard/exercicios'
    | '/dashboard/pacientes'
    | '/dashboard/transcricao'
    | '/dashboard/'
    | '/dashboard/pacientes/$id'
    | '/dashboard/pacientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/transcricao': {
      id: '/dashboard/transcricao'
      path: '/transcricao'
      fullPath: '/dashboard/transcricao'
      preLoaderRoute: typeof DashboardTranscricaoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pacientes': {
      id: '/dashboard/pacientes'
      path: '/pacientes'
      fullPath: '/dashboard/pacientes'
      preLoaderRoute: typeof DashboardPacientesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/exercicios': {
      id: '/dashboard/exercicios'
      path: '/exercicios'
      fullPath: '/dashboard/exercicios'
      preLoaderRoute: typeof DashboardExerciciosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pacientes/': {
      id: '/dashboard/pacientes/'
      path: '/'
      fullPath: '/dashboard/pacientes/'
      preLoaderRoute: typeof DashboardPacientesIndexRouteImport
      parentRoute: typeof DashboardPacientesRoute
    }
    '/dashboard/pacientes/$id': {
      id: '/dashboard/pacientes/$id'
      path: '/$id'
      fullPath: '/dashboard/pacientes/$id'
      preLoaderRoute: typeof DashboardPacientesIdRouteImport
      parentRoute: typeof DashboardPacientesRoute
    }
  }
}

interface DashboardPacientesRouteChildren {
  DashboardPacientesIdRoute: typeof DashboardPacientesIdRoute
  DashboardPacientesIndexRoute: typeof DashboardPacientesIndexRoute
}

const DashboardPacientesRouteChildren: DashboardPacientesRouteChildren = {
  DashboardPacientesIdRoute: DashboardPacientesIdRoute,
  DashboardPacientesIndexRoute: DashboardPacientesIndexRoute,
}

const DashboardPacientesRouteWithChildren =
  DashboardPacientesRoute._addFileChildren(DashboardPacientesRouteChildren)

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardExerciciosRoute: typeof DashboardExerciciosRoute
  DashboardPacientesRoute: typeof DashboardPacientesRouteWithChildren
  DashboardTranscricaoRoute: typeof DashboardTranscricaoRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardExerciciosRoute: DashboardExerciciosRoute,
  DashboardPacientesRoute: DashboardPacientesRouteWithChildren,
  DashboardTranscricaoRoute: DashboardTranscricaoRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
