from __future__ import annotations

import base64
import json
import os

from cryptography.hazmat.primitives.ciphers.aead import AESGCM


class EncryptionService:
    """
    Application-layer AES-256-GCM encryption backed by AWS KMS envelope encryption.

    Each organisation has a Data Encryption Key (DEK) generated by KMS and stored
    in encrypted form as ``encryptedDek`` inside the org's DynamoDB item.  The
    plaintext DEK is derived on-demand (one KMS Decrypt call per process start)
    and then cached in-process for the lifetime of the worker.
    """

    def __init__(self, kms_client, org_repository, *, kms_key_arn: str | None):
        if not kms_key_arn or not kms_key_arn.strip():
            raise RuntimeError(
                "PSYFLOW_KMS_KEY_ARN is required but not set. "
                "Set it to the KMS key ARN output from the CDK stack."
            )
        self._kms = kms_client
        self._org_repository = org_repository
        self._kms_key_arn = kms_key_arn.strip()
        self._dek_cache: dict[str, bytes] = {}

    def provision_org_key(self, org_id: str) -> dict:
        """
        Generates a DEK for *org_id* via KMS and returns the fields to merge
        into the org item before it is saved to DynamoDB.

        The plaintext DEK is discarded after this call; it will be re-derived
        from KMS the first time encrypt/decrypt is called for this org.
        """
        if not self._kms_key_arn:
            raise RuntimeError("PSYFLOW_KMS_KEY_ARN is not configured")

        response = self._kms.generate_data_key(
            KeyId=self._kms_key_arn,
            KeySpec="AES_256",
            EncryptionContext={"orgId": org_id},
        )
        encrypted_dek = base64.b64encode(response["CiphertextBlob"]).decode()
        return {"encryptedDek": encrypted_dek, "keyVersion": 1}

    def _get_dek(self, org_id: str) -> bytes:
        if org_id in self._dek_cache:
            return self._dek_cache[org_id]

        org = self._org_repository.get_by_id(org_id)
        if org is None:
            raise ValueError(f"Organisation not found: {org_id}")

        encrypted_dek_b64: str | None = org.get("encryptedDek")
        if not encrypted_dek_b64:
            raise ValueError(f"Organisation {org_id} has no encryption key provisioned")

        encrypted_dek = base64.b64decode(encrypted_dek_b64)
        response = self._kms.decrypt(
            CiphertextBlob=encrypted_dek,
            EncryptionContext={"orgId": org_id},
        )
        dek: bytes = response["Plaintext"]
        self._dek_cache[org_id] = dek
        return dek

    def encrypt(self, org_id: str, plaintext: str) -> str:
        """
        Encrypts *plaintext* with the org's DEK using AES-256-GCM.
        Returns a compact JSON envelope: ``{"v":1,"n":"<nonce_b64>","c":"<ct_b64>"}``.
        """
        dek = self._get_dek(org_id)
        nonce = os.urandom(12)  # 96-bit nonce – standard for GCM
        ct = AESGCM(dek).encrypt(nonce, plaintext.encode("utf-8"), None)
        return json.dumps(
            {"v": 1, "n": base64.b64encode(nonce).decode(), "c": base64.b64encode(ct).decode()},
            separators=(",", ":"),
        )

    def decrypt(self, org_id: str, envelope: str) -> str:
        """Decrypts a JSON envelope produced by :meth:`encrypt`."""
        dek = self._get_dek(org_id)
        data = json.loads(envelope)
        nonce = base64.b64decode(data["n"])
        ct = base64.b64decode(data["c"])
        return AESGCM(dek).decrypt(nonce, ct, None).decode("utf-8")
